<?php

return [
    'settings' => [
        'app_info' => [
            'app_title' => 'Take Me',
            'image_title' => 'Take Me',
            'app_name' => 'Take Me',
        ],
    ],
    'app_settings' => [
        'site_title' => 'Take Me',
        'meta_description' => 'Book rides and get around with Take Me.',
        'site_favicon' => '',
        'site_logo' => '',
        'site_dark_logo' => '',
        'contact_email' => '',
        'contact_number' => '',
        'company_name' => 'Your Company',
        'language_option' => 'ar',
        'twitter_url' => '',
        'facebook_url' => '',
        'instagram_url' => '',
        'linkedin_url' => '',
        'help_support_url' => '',
        'site_copyright' => 'All rights reserved.',
    ],
    'frontend_data' => [
        'our_mission' => [
            'title' => 'Our Mission',
            'subtitle' => '',
            'description' => 'We aim to deliver safe, reliable rides for everyone.',
            'image' => '',
        ],
        'why_choose' => [
            'title' => 'Why Choose Us',
            'subtitle' => '',
            'description' => 'Quality drivers, transparent pricing, and quick pickups.',
            'image' => '',
        ],
        'client_testimonials' => [
            'title' => 'Client Testimonials',
            'subtitle' => 'What riders are saying',
            'description' => 'Great service and friendly drivers.',
            'image' => '',
        ],
    ],
    'dashboard' => [
        'totalDrivers' => 0,
        'pendingDrivers' => 0,
        'totalRiders' => 0,
        'totalRides' => 0,
        'todayEarnings' => 0.0,
        'monthEarnings' => 0.0,
        'totalEarnings' => 0.0,
        'sosCount' => 0,
        'recentRides' => [],
        'newRideRequests' => 0,
        'pendingComplaints' => 0,
        'pendingWithdrawRequests' => 0,
        'pendingSupportRequests' => 0,
    ],
    'riders' => [
        [
            'uid' => 'mock-rider-1',
            'first_name' => 'Test',
            'last_name' => 'Rider One',
            'email' => 'rider1@example.com',
            'phone' => '+966500000001',
            'username' => 'rider1',
            'address' => 'Riyadh',
            'created_at' => '2024-01-01 10:00:00',
        ],
        [
            'uid' => 'mock-rider-2',
            'first_name' => 'Test',
            'last_name' => 'Rider Two',
            'email' => 'rider2@example.com',
            'phone' => '+966500000002',
            'username' => 'rider2',
            'address' => 'Jeddah',
            'created_at' => '2024-01-02 11:30:00',
        ],
    ],
    'drivers' => [
        [
            'id' => 'mock-driver-1',
            'uid' => 'mock-driver-1',
            'name' => 'Driver One',
            'email' => 'driver1@example.com',
            'phone' => '+966500000101',
            'cityId' => 'riyadh',
            'verificationStatus' => 'approved',
            'isOnline' => false,
            'isAvailable' => false,
            'lastSeenAt' => '2024-01-03 09:00:00',
            'created_at' => '2024-01-01 09:00:00',
        ],
        [
            'id' => 'mock-driver-2',
            'uid' => 'mock-driver-2',
            'name' => 'Driver Two',
            'email' => 'driver2@example.com',
            'phone' => '+966500000102',
            'cityId' => 'jeddah',
            'verificationStatus' => 'pending',
            'isOnline' => true,
            'isAvailable' => false,
            'lastSeenAt' => '2024-01-04 12:30:00',
            'created_at' => '2024-01-02 10:30:00',
        ],
    ],
    'mock_pending_drivers' => [
        [
            'id' => 'mock-driver-2',
            'uid' => 'mock-driver-2',
            'name' => 'Driver Two',
            'email' => 'driver2@example.com',
            'phone' => '+966500000102',
            'cityId' => 'jeddah',
            'verificationStatus' => 'pending',
            'lastSeenAt' => '2024-01-04 12:30:00',
            'created_at' => '2024-01-02 10:30:00',
        ],
    ],
    'pending_drivers' => [
        [
            'uid' => 'mock-driver-3',
            'name' => 'Driver Three',
            'email' => 'driver3@example.com',
            'phone' => '+966500000103',
            'cityId' => 'riyadh',
            'verificationStatus' => 'pending',
            'lastSeenAt' => '2024-01-05 08:20:00',
            'created_at' => '2024-01-03 08:20:00',
        ],
        [
            'uid' => 'mock-driver-4',
            'name' => 'Driver Four',
            'email' => 'driver4@example.com',
            'phone' => '+966500000104',
            'cityId' => 'jeddah',
            'verificationStatus' => 'in_review',
            'lastSeenAt' => '2024-01-06 14:45:00',
            'created_at' => '2024-01-04 14:45:00',
        ],
    ],
    'mock_driver_documents' => [
        'profile' => 'https://example.com/profile.jpg',
        'license' => 'https://example.com/license.jpg',
        'insurance' => 'https://example.com/insurance.jpg',
        'car_image' => 'https://example.com/car.jpg',
        'car_license' => 'https://example.com/car-license.jpg',
        'medical' => 'https://example.com/medical.jpg',
    ],
    'driver_map' => [
        [
            'id' => 'mock-driver-1',
            'display_name' => 'Driver One',
            'contact_number' => '+966500000101',
            'latitude' => 24.7136,
            'longitude' => 46.6753,
            'is_online' => true,
            'is_available' => true,
        ],
    ],
    'driver_docs' => [
        [
            'uid' => 'mock-driver-1',
            'name' => 'Driver One',
            'email' => 'driver1@example.com',
            'phone' => '+966500000101',
            'verificationStatus' => 'approved',
            'created_at' => '2024-01-01 09:00:00',
            'docs' => [
                'profile' => 'https://example.com/profile.jpg',
                'license' => 'https://example.com/license.jpg',
                'insurance' => 'https://example.com/insurance.jpg',
                'car_license' => 'https://example.com/car-license.jpg',
                'car_image' => 'https://example.com/car.jpg',
            ],
        ],
    ],
    'coupons' => [
        [
            'code' => 'WELCOME10',
            'title' => 'Welcome',
            'coupon_type' => 'all',
            'discount_type' => 'percent',
            'discount' => 10,
            'minimum_amount' => 0,
            'maximum_discount' => 50,
            'start_date' => '2024-01-01',
            'end_date' => '2024-12-31',
            'usage_limit_per_rider' => 1,
            'status' => 'active',
            'description' => 'Welcome coupon',
            'created_at' => '2024-01-01 00:00:00',
        ],
        [
            'code' => 'FIXED5',
            'title' => 'Fixed Discount',
            'coupon_type' => 'all',
            'discount_type' => 'fixed',
            'discount' => 5,
            'minimum_amount' => 20,
            'maximum_discount' => 5,
            'start_date' => '2024-01-01',
            'end_date' => '2024-12-31',
            'usage_limit_per_rider' => 2,
            'status' => 'inactive',
            'description' => '',
            'created_at' => '2024-01-02 00:00:00',
        ],
    ],
    'payments_cash' => [
        [
            'id' => 'pay-1',
            'source' => 'rides',
            'rider_uid' => 'rider-1',
            'driver_uid' => 'driver-1',
            'total' => 25,
            'currency' => 'SAR',
            'payment_method' => 'cash',
            'payment_status' => 'unpaid',
            'created_at' => '2024-01-10 12:00:00',
        ],
    ],
    'payments_online' => [
        [
            'id' => 'pay-2',
            'source' => 'rides',
            'rider_uid' => 'rider-2',
            'driver_uid' => 'driver-2',
            'total' => 40,
            'currency' => 'SAR',
            'payment_method' => 'online',
            'payment_status' => 'paid',
            'created_at' => '2024-01-11 10:00:00',
        ],
    ],
    'payments_wallet' => [
        [
            'id' => 'pay-3',
            'source' => 'ride_requests',
            'rider_uid' => 'rider-3',
            'driver_uid' => 'driver-3',
            'total' => 15,
            'currency' => 'SAR',
            'payment_method' => 'wallet',
            'payment_status' => 'paid',
            'created_at' => '2024-01-12 09:30:00',
        ],
    ],
    'offers' => [
        [
            'id' => 'offer-1',
            'title' => 'عرض تجريبي',
            'riderName' => 'Rider One',
            'riderPhone' => '+966500000001',
            'basePrice' => 30,
            'currency' => 'SAR',
            'discountPercent' => 0,
            'pickupAddress' => 'الرياض',
            'dropoffAddress' => 'جدة',
            'status' => 'new',
            'submittedAt' => '2024-01-10 12:00:00',
            'updatedAt' => '2024-01-10 12:00:00',
            'assignedDriverUid' => '',
            'bidsCount' => 0,
        ],
    ],
    'wallet_topups' => [
        [
            'id' => 'topup-1',
            'uid' => 'mock-driver-1',
            'amount' => 50,
            'note' => 'تحويل تجريبي',
            'status' => 'pending',
            'created_at' => '2024-01-10 11:00:00',
            'receipt_url' => '',
        ],
    ],
    'offer_bidders' => [
        [
            'uid' => 'mock-driver-1',
            'name' => 'Driver One',
            'phone' => '+966500000101',
            'is_online' => true,
            'is_available' => true,
        ],
    ],
    'surge_rules' => [
        [
            'id' => 'rule-1',
            'cityId' => 'riyadh',
            'cityName' => 'الرياض',
            'serviceId' => 'taxi',
            'type' => 'weather',
            'increaseType' => 'percent',
            'increaseValue' => 10,
            'description' => 'زيادة بسبب المطر',
            'weather' => 'rain',
            'day' => 'all',
            'timeFrom' => '08:00',
            'timeTo' => '10:00',
            'status' => 'active',
            'createdAt' => '2024-01-10 12:00:00',
        ],
    ],
    'pricing' => [
        [
            'id' => 'riyadh-taxi',
            'cityId' => 'riyadh',
            'cityName' => 'الرياض',
            'serviceId' => 'taxi',
            'baseFare' => 10,
            'perKm' => 2,
            'perMin' => 1,
            'minFare' => 12,
            'currency' => 'SAR',
            'isActive' => true,
            'createdAt' => '2024-01-10 12:00:00',
        ],
    ],
    'pricing_modifiers' => [
        [
            'id' => 'mod-1',
            'type' => 'time',
            'cityId' => 'riyadh',
            'cityName' => 'الرياض',
            'serviceId' => 'taxi',
            'currency' => 'SAR',
            'modifierMode' => 'percent',
            'modifierValue' => 10,
            'day' => 'all',
            'startTime' => '08:00',
            'endTime' => '10:00',
            'weatherCondition' => '',
            'placeKey' => '',
            'placeName' => '',
            'zoneId' => '',
            'surgeTag' => '',
            'description' => 'قاعدة وقت',
            'isActive' => true,
            'priority' => 1,
            'createdAt' => '2024-01-10 12:00:00',
        ],
    ],
    'cities' => [
        [
            'id' => 'riyadh',
            'name' => 'الرياض',
        ],
        [
            'id' => 'jeddah',
            'name' => 'جدة',
        ],
    ],
    'mock_school_monthly_employee' => [
        [
            'id' => 'emp-1',
            'created_at' => '2024-01-10 10:00:00',
            'service_type' => 'توصيل موظفين',
            'status' => 'pending',
            'phone' => '+966500000201',
            'notes' => 'ملاحظة تجريبية',
            'persons' => '3',
            'is_shift_work' => '1',
            'days_count' => '5',
            'home' => 'الرياض (24.7136,46.6753)',
            'dest' => 'الرياض (24.7136,46.6753)',
            'driver_arrival_time' => '08:00',
            'start_time' => '08:30',
            'end_time' => '16:00',
            'shifts_text' => 'sat 11:00-2:00',
        ],
    ],
    'mock_school_monthly_schools' => [
        [
            'id' => 'sch-1',
            'created_at' => '2024-01-11 09:00:00',
            'service_type' => 'توصيل مدارس',
            'status' => 'pending',
            'phone' => '+966500000202',
            'notes' => 'ملاحظة تجريبية',
            'persons' => '2',
            'is_shift_work' => '0',
            'days_count' => '5',
            'home' => 'جدة (21.4858,39.1925)',
            'dest' => 'جدة (21.4858,39.1925)',
            'driver_arrival_time' => '07:30',
            'start_time' => '08:00',
            'end_time' => '13:00',
            'shifts_text' => 'sun 08:00-13:00',
        ],
    ],
    'mock_airport_requests' => [
        [
            'id' => 'air-1',
            'created_at' => '2024-01-12 12:00:00',
            'status' => 'pending',
            'driver_time' => '14:00',
            'service_type' => 'airport_transfer',
            'from_address' => 'Riyadh',
            'to_address' => 'Airport',
            'from_coords' => '24.7136,46.6753',
            'to_coords' => '24.9576,46.6988',
        ],
    ],
    'mock_special_needs_requests' => [
        [
            'id' => 'sn-1',
            'created_at' => '2024-01-13 15:00:00',
            'status' => 'pending',
            'name' => 'User One',
            'email' => 'user@example.com',
            'phone' => '+966500000203',
            'notes' => 'بدون ملاحظات',
            'service_type' => 'special_needs_ride',
            'user_id' => 'user-1',
            'from_address' => 'Riyadh',
            'to_address' => 'Hospital',
            'from_coords' => '24.7136,46.6753',
            'to_coords' => '24.7400,46.7000',
        ],
    ],
    'rides_admin' => [
        'all' => [
            [
                'id' => 'ride-1',
                'source' => 'rides',
                'created_at' => '2024-01-10 12:00:00',
                'status' => 'completed',
                'rider_uid' => 'rider-1',
                'driver_uid' => 'driver-1',
                'pickup_address' => 'Riyadh',
                'dropoff_address' => 'Jeddah',
                'fare_total' => 25,
            ],
        ],
        'completed' => [
            [
                'id' => 'ride-1',
                'source' => 'rides',
                'created_at' => '2024-01-10 12:00:00',
                'status' => 'completed',
                'rider_uid' => 'rider-1',
                'driver_uid' => 'driver-1',
                'pickup_address' => 'Riyadh',
                'dropoff_address' => 'Jeddah',
                'fare_total' => 25,
            ],
        ],
        'today' => [],
        'cancelled' => [],
        'inprogress' => [],
    ],
    'mock_ride_rows' => [
        [
            'id' => 'ride-1',
            'source' => 'rides',
            'created_at' => '2024-01-10 12:00:00',
            'status' => 'completed',
            'rider_uid' => 'rider-1',
            'driver_uid' => 'driver-1',
            'pickup_address' => 'Riyadh',
            'dropoff_address' => 'Jeddah',
            'fare_total' => 25,
            'currency' => 'SAR',
            'payment_method' => 'cash',
            'payment_status' => 'paid',
        ],
        [
            'id' => 'ride-2',
            'source' => 'ride_requests',
            'created_at' => '2024-01-11 09:30:00',
            'status' => 'cancelled',
            'rider_uid' => 'rider-2',
            'driver_uid' => 'driver-2',
            'pickup_address' => 'Jeddah',
            'dropoff_address' => 'Makkah',
            'fare_total' => 0,
            'currency' => 'SAR',
            'payment_method' => '',
            'payment_status' => '',
        ],
    ],
    'mock_rides' => [
        'all' => [
            [
                'id' => 'ride-1',
                'source' => 'rides',
                'createdAt' => '2024-01-10 12:00:00',
                'status' => 'completed',
                'riderUid' => 'rider-1',
                'driverUid' => 'driver-1',
                'pickupAddress' => 'Riyadh',
                'dropoffAddress' => 'Jeddah',
                'fareTotal' => 25,
                'currency' => 'SAR',
                'paymentMethod' => 'cash',
                'paymentStatus' => 'paid',
                'riderName' => 'Rider One',
                'driverName' => 'Driver One',
            ],
        ],
        'completed' => [
            [
                'id' => 'ride-1',
                'source' => 'rides',
                'createdAt' => '2024-01-10 12:00:00',
                'status' => 'completed',
                'riderUid' => 'rider-1',
                'driverUid' => 'driver-1',
                'pickupAddress' => 'Riyadh',
                'dropoffAddress' => 'Jeddah',
                'fareTotal' => 25,
                'currency' => 'SAR',
                'paymentMethod' => 'cash',
                'paymentStatus' => 'paid',
                'riderName' => 'Rider One',
                'driverName' => 'Driver One',
            ],
        ],
        'today' => [],
        'cancelled' => [],
        'inprogress' => [],
    ],
    'mock_ride_requests' => [
        [
            'id' => 'req-1',
            'source' => 'ride_requests',
            'createdAt' => '2024-01-11 10:00:00',
            'status' => 'pending',
            'riderUid' => 'rider-2',
            'driverUid' => '',
            'pickupAddress' => 'Riyadh',
            'dropoffAddress' => 'Dammam',
            'fareTotal' => 12,
            'currency' => 'SAR',
            'paymentMethod' => 'cash',
            'paymentStatus' => 'unknown',
            'riderName' => 'Rider Two',
            'driverName' => '',
        ],
    ],
    'mock_payments_online' => [
        [
            'id' => 'pay-1',
            'riderUid' => 'rider-1',
            'driverUid' => 'driver-1',
            'total' => 25,
            'currency' => 'SAR',
            'paymentMethod' => 'online',
            'paymentStatus' => 'paid',
            'createdAt' => '2024-01-10 12:00:00',
        ],
    ],
    'mock_payments_cash' => [
        [
            'id' => 'pay-2',
            'riderUid' => 'rider-2',
            'driverUid' => 'driver-2',
            'total' => 15,
            'currency' => 'SAR',
            'paymentMethod' => 'cash',
            'paymentStatus' => 'paid',
            'createdAt' => '2024-01-11 09:30:00',
        ],
    ],
    'mock_payments_wallet' => [
        [
            'id' => 'pay-3',
            'riderUid' => 'rider-3',
            'driverUid' => 'driver-3',
            'total' => 12,
            'currency' => 'SAR',
            'paymentMethod' => 'wallet',
            'paymentStatus' => 'paid',
            'createdAt' => '2024-01-12 18:45:00',
        ],
    ],
    'mock_admins' => [
        [
            'id' => 'admin@example.com',
            'email' => 'admin@example.com',
            'name' => 'Admin',
            'is_active' => true,
            'roles' => ['super_admin'],
            'created_at' => '2024-01-01 00:00:00',
        ],
        [
            'id' => 'subadmin@example.com',
            'email' => 'subadmin@example.com',
            'name' => 'Sub Admin',
            'is_active' => true,
            'roles' => ['sub_admin'],
            'created_at' => '2024-01-02 00:00:00',
        ],
    ],
    'mail_templates' => [
        'new_ride_requested' => [
            'type' => 'new_ride_requested',
            'subject' => 'New ride requested',
            'body_html' => '<p>A new ride was requested.</p>',
            'body_text' => 'A new ride was requested.',
        ],
        'bid_placed' => [
            'type' => 'bid_placed',
            'subject' => 'Bid placed',
            'body_html' => '<p>A bid has been placed.</p>',
            'body_text' => 'A bid has been placed.',
        ],
        'arriving' => [
            'type' => 'arriving',
            'subject' => 'Driver arriving',
            'body_html' => '<p>Your driver is arriving.</p>',
            'body_text' => 'Your driver is arriving.',
        ],
    ],
    'mock_sos_alerts' => [
        [
            'id' => 'sos-1',
            'ride_id' => 'ride-1',
            'name' => 'Rider One',
            'phone' => '+966500000001',
            'address' => 'Riyadh → Jeddah',
            'sos_location' => '24.7136,46.6753',
            'map_url' => 'https://www.google.com/maps?q=24.7136,46.6753',
            'created_at' => '2024-01-10 12:05:00',
            'status' => 'open',
        ],
    ],
    'sub_admins' => [
        [
            'uid' => 'mock-subadmin-1',
            'name' => 'Sub Admin One',
            'email' => 'subadmin1@example.com',
            'is_active' => true,
            'created_at' => '2024-01-05 09:15:00',
        ],
        [
            'uid' => 'mock-subadmin-2',
            'name' => 'Sub Admin Two',
            'email' => 'subadmin2@example.com',
            'is_active' => false,
            'created_at' => '2024-01-10 14:45:00',
        ],
    ],
];
